import { useNavigate } from 'react-router-dom';
import { useCallback } from 'react';



export const useImageGen = (setShowDrawing, setIsLoading, setError) => {
  const navigate = useNavigate();

  const handleSearch = (searchQuery, displayText, onSearch) => (e) => {
    e.preventDefault();
    
    onSearch(searchQuery || displayText);
  };

  const handleImageReady = useCallback(async (imageData) => {
    setShowDrawing(false);
    setIsLoading(true);
    setError(null);

    try {
      // Make the API request to create image-to-3d task
      const response = await fetch(`${process.env.REACT_APP_API_BASE_URL}/api/image-to-3d`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          imageData,
          artStyle: 'realistic',
          aiModel: 'meshy-4'
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.details || 'Failed to process image');
      }

      const data = await response.json();
      const taskId = data.result;

      // Poll for task completion
      let taskStatus;
      do {
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        const statusResponse = await fetch(
          `${process.env.REACT_APP_API_BASE_URL}/api/text-to-3d/${taskId}`
        );
        
        if (!statusResponse.ok) {
          throw new Error('Failed to check task status');
        }
        
        taskStatus = await statusResponse.json();
        
        if (taskStatus.status === 'FAILED') {
          throw new Error(taskStatus.task_error?.message || 'Task failed');
        }
      } while (taskStatus.status === 'PENDING' || taskStatus.status === 'IN_PROGRESS');

      // Navigate to editor with the generated model
      if (taskStatus.status === 'SUCCEEDED') {
        navigate('/editor', {
          state: {
            modelUrl: taskStatus.model_urls.glb,
            taskId: taskStatus.id,
            modelDetails: {
              name: 'Generated from Image',
              format: 'GLB',
              size: 'Generated by Meshy',
              created: new Date(taskStatus.created_at).toLocaleDateString()
            }
          },
          replace: true
        });
      }
    } catch (error) {
      console.error('Image processing failed:', error);
      setError(error.message);
    } finally {
      setIsLoading(false);
    }
  }, [navigate, setShowDrawing, setIsLoading, setError]);

  return {
    handleSearch,
    handleImageReady
  };
};